name: Homebrew Release

on:
  release:
    types: [published]

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release info
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate SHA256
        id: calculate_sha
        run: |
          TARBALL_URL="${{ steps.get_release.outputs.tarball_url }}"
          SHA=$(curl -sL "$TARBALL_URL" | shasum -a 256 | cut -d ' ' -f 1)
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      - name: Create or update Homebrew formula
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: data-catering/homebrew-insta-infra
          event-type: update-formula
          client-payload: '{"version": "${{ steps.get_release.outputs.tag_name }}", "sha256": "${{ steps.calculate_sha.outputs.sha256 }}"}' 